apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-html
data:
  index.html: |-
    <html><body>TEST</body></html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    appver: v1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: data
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 500m
              memory: 1024Mi
      volumes:
        - name: data
          configMap:
            name: test-html
