apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    appver: v2
spec:
  replicas: 2
  revisionHistoryLimit: 100
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        appver: v2
    spec:
      containers:
        - image: nginx:latest
          name: nginx
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: data
          ports:
            - containerPort: 80
      volumes:
        - name: data
          configMap:
            name: v2-html
